#!/bin/sh
# 官方 LuCI 默认 lang=auto，会跟浏览器语言走（英文浏览器就是英文界面）
uci -q set luci.main.lang='zh_cn'
if [ -d /www/luci-static/argon ]; then
	uci -q set luci.main.mediaurlbase='/luci-static/argon'
fi
uci commit luci
exit 0
