#!/bin/sh
# LuCI default language zh_cn and Argon theme (falls back silently if theme absent)
uci -q set luci.main.lang='zh_cn'
if [ -d /www/luci-static/argon ]; then
	uci -q set luci.main.mediaurlbase='/luci-static/argon'
	uci -q set luci.themes.Argon='/luci-static/argon'
fi
uci commit luci
exit 0
